export const FooterStyles = {
  wrapper: {
    height: '340px',
    backgroundColor: 'black',
    boxShadow: '0px -100px 110px black',
    marginTop: '4rem',
    display: 'flex',
  },
  footerSection: {
    width: '93%',
    margin: '0px auto',
    display: 'flex',
    justifyContent: 'space-between',
    alignSelf: 'flex-end',
  },
  footerInfo: {
    width: '100%',
    listStyleType: 'none',
    color: '#CFCFCF',
    display: 'flex',
    margin: 0,
    height: '100%',
    alignItems: 'center',
    fontFamily: 'Bitter',
    fontSize: '34px',
    justifyContent: 'space-evenly',
    padding: 0,
  },
  logoPart: {
    display: 'flex',
    flexDirection: 'column' as 'column',
    alignItems: 'center',
    height: '100%',
    justifyContent: 'center',
    fontFamily: 'Bitter',
  },
  infoItem: {
    height: '60%',
    display: 'flex',
    flexDirection: 'column' as 'column',
    justifyContent: 'space-between',
  },
  currency: {
    display: 'flex',
    width: '88%',
    justifyContent: 'space-between',
    gap: '10px',
  },
  language: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  socialNetworks: {
    display: 'flex',
    flexDirection: 'column' as 'column',
    height: '63%',
    justifyContent: 'space-between',
    width: '1%',
  },
};
