export const aboutmeStyles = {
  barderProfileWrapper: {
    background: '#000',
    boxShadow: 'black 0px 305px 90px',
  },
  firstSection: {
    display: 'flex',
    justifyContent: 'center',
    width: '88%',
    margin: 'auto',
    paddingTop: '173px',
  },
  whyme: {
    fontSize: '65px',
    color: 'white',
    height: '550px',
    display: 'flex',
    flexDirection: 'column' as 'column',
    justifyContent: 'space-between',
    paddingTop: '20px',
    zIndex: 1,
  },
  whymeP: {
    margin: 0,
    fontFamily: 'Drum',
    fontSize: '115px',
    paddingBottom: '20px',
  },
  pStyle: {
    margin: 0,
    fontFamily: 'Drum',
    fontSize: '50px',
  },
  inscription: {
    width: '88%',
    margin: 'auto',
    opacity: '0.85',
    paddingTop: '130px',
    paddingBottom: '50px',
    boxShadow: 'black 0px -125px 90px',
  },
  inscrText: {
    color: '#fff',
    fontSize: '29px',
    fontFamily: 'Bitter',
    fontWeight: '100',
  },
  portfolioWrap: { width: '88%', margin: 'auto' },
  portfolioTitle: { color: '#fff', fontFamily: 'Drum', fontSize: '80px' },
  photosRow: {
    display: 'flex',
    justifyContent: 'space-around',
    width: '100%',
    marginBottom: '90px',
    flexWrap: 'wrap' as 'wrap',
  },
};
