export const signInFormMobileStyles = {
  signinWrapper: {
    position: 'fixed' as 'fixed',
    display: 'flex',
    width: '90%',
    flexDirection: 'column' as 'column',
    zIndex: 10,
    alignItems: 'center',
    backgroundColor: '#fff',
    top: 'calc(50% - 247.5px)',
  },
  signInTitle: {
    position: 'relative' as 'relative',
    textAlign: 'center' as 'center',
    width: '100%',
    marginBottom: '45px',
    fontSize: '27px',
    color: '#444444',
    fontFamily: 'Drum',
  },
  closeButton: {
    background: 'transparent',
    color: '#444444',
    border: 'none',
    position: 'absolute' as 'absolute',
    right: '-9px',
    top: '7px',
    fontFamily: 'Drum',
    fontSize: '40px',
    cursor: 'pointer',
  },
  emailLabel: {
    display: 'block',
    fontFamily: 'Bitter',
    fontSize: '19px',
    color: '#444444',
  },
  emailInput: {
    width: '100%',
    backgroundColor: 'transparent',
    border: 'none',
    height: '30px',
    fontFamily: 'Bitter',
    color: '#444444',
    fontSize: '16px',
    fontWeight: '600',
    marginLeft: '3px',
  },
  passwordLabelWrap: {
    display: 'flex',
    marginTop: '20px',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  passwordLabel: {
    fontFamily: 'Bitter',
    fontSize: '18px',
    color: '#444444',
  },
  passwordInput: {
    width: '100%',
    backgroundColor: 'transparent',
    border: 'none',
    fontFamily: 'Bitter',
    height: '30px',
    color: '#444444',
    fontSize: '16px',
    fontWeight: '600',
    marginLeft: '5px',
  },
  signinBtnWrap: {
    display: 'flex',
    width: '100%',
    justifyContent: 'center',
    marginTop: '45px',
  },
  signinBtn: {
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    padding: 0,
  },
  submitSectionWrap: {
    display: 'flex',
    marginTop: '30px',
    justifyContent: 'center',
  },
  signupOfferWrap: {
    display: 'flex',
    alignItems: 'center',
    fontFamily: 'Bitter',
    marginLeft: '1px',
  },
  forgotPassword: {
    margin: 0,
    fontFamily: 'Bitter',
    whiteSpace: 'nowrap' as 'nowrap',
    alignSelf: 'center',
    fontSize: '16px',
    paddingRight: '9px',
    color: '#6d6d6d',
  },
  donthaveAcc1: {
    margin: 0,
    paddingRight: '10px',
    whiteSpace: 'nowrap' as 'nowrap',
    fontSize: '11px',
    color: '#6d6d6d',
  },
  donthaveAcc2: {
    margin: 0,
    fontSize: '22px',
    fontWeight: 600,
    color: '#555555',
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    fontFamily: 'inherit',
    padding: '0px',
  },
  or: {
    fontFamily: 'Drum',
    color: '#444444',
    width: '14%',
    textAlign: 'center' as 'center',
    fontSize: '25px',
    margin: '0px',
    paddingBottom: '13px',
  },
  signinWithWrap: {
    display: 'flex',
    width: '90%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '25px',
  },
  signinWith: {
    fontFamily: 'Bitter',
    fontSize: '19px',
    color: '#444444',
    fontWeight: 100,
    margin: 0,
    alignSelf: 'center',
    width: '37%',
  },
  icons: {
    display: 'flex',
    width: '63%',
    justifyContent: 'space-around',
  },
  leftTop: {
    position: 'absolute' as 'absolute',
    left: '-4px',
    top: '-4px',
    width: '42px',
  },
  rightTop: {
    position: 'absolute' as 'absolute',
    right: '-4px',
    top: '-4px',
    width: '42px',
  },
  rightBot: {
    position: 'absolute' as 'absolute',
    right: '-4px',
    bottom: '-4px',
    width: '42px',
  },
  leftBot: {
    position: 'absolute' as 'absolute',
    left: '-4px',
    bottom: '-4px',
    width: '42px',
  },
  dividerBot: { display: 'flex', width: '90%', margin: '0 auto' },
};
